[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
macros = { path = "../macros" }
log = "0.4.27"
thiserror = "2.0.16"
serde = { version = "1.0", features = ["derive"] }
