apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    uid: loki
    url: http://taliro-loki:3100
    isDefault: true
    editable: true
    jsonData:
      maxLines: 1000
